[package]
name = "easy-zip-to-cbz"
version = "0.5.0"
authors = ["mrtambour <6724649+mrtambour@users.noreply.github.com>"]
edition = "2021"

[dependencies]
simple_config_parser = "1.0.0"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 2
lto = true
